spring:
  application:
    name: AI-Agent
  profiles:
    active: local
#  mail:
#    host: smtp.qq.com
#    port: 465
#    username: 邮箱       # 替换为你的 QQ 邮箱
#    password: 授权码 # 替换为 QQ 邮箱授权码（非登录密码）
#    protocol: smtp
#    properties:
#      mail:
#        smtp:
#          ssl:
#            enable: true
#          auth: true
#  ai:
#    dashscope:
#      # 需要替换为你自己的 key
#      api-key: key
#      chat:
#        options:
#          model: MiniMax-M2.5
  # ollama??????
#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: gemma3:1b
server:
  port: 9888
  servlet:
    context-path: /rest # ??????rest??
# springdoc-openapi ??????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.study.aiagent.controller # ????????
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
#logging:
#  level:
#    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
#search:
#  api-key: key # 替换为你的搜索api key
