spring:
  application:
    name: AI-Agent
  profiles:
    active: local
  # ollama??????
#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: gemma3:1b
server:
  port: 9888
  servlet:
    context-path: /rest # ??????rest??
# springdoc-openapi ??????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.study.aiagent.controller # ????????
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
